esphome:
  name: patio-table
  platform: esp32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-patio-table
    password: salaisuus

captive_portal:

fan:
  - id: pump
    name: Patio table pump
    platform: speed
    output: pwm_pump

light:
  - id: lights_river
    name: Patio table river lights
    platform: partition
    segments:
      - single_light_id: led0
      - single_light_id: led1
      - single_light_id: led2
      - single_light_id: led3
      - single_light_id: led4
      - single_light_id: led5
      - single_light_id: led6
      - single_light_id: led7
      - single_light_id: led8
      - single_light_id: led9
    effects:
      - flicker:
          alpha: 95%
          intensity: 3%

  - id: lights_waterfall
    name: Patio table waterfall lights
    platform: partition
    segments:
      - single_light_id: big_led0
      - single_light_id: big_led1
      - single_light_id: big_led2
      - single_light_id: big_led3

  - id: led0
    name: led0
    platform: monochromatic
    output: pwm_led0
    effects:
      - flicker:
          alpha: 95%
          intensity: 3%
  - id: led1
    name: led1
    platform: monochromatic
    output: pwm_led1
    effects:
      - flicker:
          alpha: 95%
          intensity: 3%
  - id: led2
    name: led2
    platform: monochromatic
    output: pwm_led2
    effects:
      - flicker:
          alpha: 95%
          intensity: 3%
  - id: led3
    platform: monochromatic
    output: pwm_led3
  - id: led4
    platform: monochromatic
    output: pwm_led4
  - id: led5
    platform: monochromatic
    output: pwm_led5
  - id: led6
    platform: monochromatic
    output: pwm_led6
  - id: led7
    platform: monochromatic
    output: pwm_led7
  - id: led8
    platform: monochromatic
    output: pwm_led8
  - id: led9
    platform: monochromatic
    output: pwm_led9

  - id: big_led0
    platform: monochromatic
    output: pwm_big_led0
  - id: big_led1
    platform: monochromatic
    output: pwm_big_led1
  - id: big_led2
    platform: monochromatic
    output: pwm_big_led2
  - id: big_led3
    platform: monochromatic
    output: pwm_big_led3

# time:
#   - platform: sntp
#     on_time:
#       - cron: 0 0 16 * * *
#         then:
#           - light.turn_on:
#               id: light0
#               brightness: 100%
#       - cron: 0 0 3 * * *
#         then:
#           - light.turn_off: light0

output:
  - id: pwm_pump
    platform: ledc
    pin: GPIO13
    frequency: 19531

  - id: pwm_led0
    platform: ledc
    pin: GPIO15
    frequency: 19531
  - id: pwm_led1
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm_led2
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm_led3
    platform: ledc
    pin: GPIO7
    frequency: 19531
  - id: pwm_led4
    platform: ledc
    pin: GPIO32
    frequency: 19531
  - id: pwm_led5
    platform: ledc
    pin: GPIO33
    frequency: 19531
  - id: pwm_led6
    platform: ledc
    pin: GPIO25
    frequency: 19531
  - id: pwm_led7
    platform: ledc
    pin: GPIO26
    frequency: 19531
  - id: pwm_led8
    platform: ledc
    pin: GPIO27
    frequency: 19531
  - id: pwm_led9
    platform: ledc
    pin: GPIO14
    frequency: 19531

  - id: pwm_big_led0
    platform: ledc
    pin: GPIO8
    frequency: 19531
  - id: pwm_big_led1
    platform: ledc
    pin: GPIO19
    frequency: 19531
  - id: pwm_big_led2
    platform: ledc
    pin: GPIO22
    frequency: 19531
  - id: pwm_big_led3
    platform: ledc
    pin: GPIO21
    frequency: 19531
