
substitutions:
  name: light-bed-back
  platform: esp32
  board: pico32

<<: !include ../config.yaml

light:
  - id: light0
    name: Bed back
    platform: monochromatic
    output: pwm0

output:
  - id: pwm0
    platform: ledc
    pin: GPIO4
    frequency: 30000
