esphome:
  name: light-fireplace
  platform: ESP32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-fireplace
    password: salaisuus

captive_portal:

light:
  - id: light0
    name: Fireplace
    platform: rgb
    red: pwm0ch1
    green: pwm0ch0
    blue: pwm0ch2
    default_transition_length: 10ms

sun:
  latitude: 62.600990°
  longitude: 29.763531°
  on_sunset:
    - then:
        - light.turn_on:
            id: light0
            brightness: 50%
            red: 100%
            green: 50%
            blue: 0%

time:
  - platform: sntp
    on_time:
      - cron: 0 0 22 * * *
        then:
          - light.turn_on:
              id: light0
              brightness: 50%
              red: 100%
              green: 50%
              blue: 0%
      - cron: 0 0 4 * * *
        then:
          - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531
