
substitutions:
  name: light-garden
  platform: esp32
  board: pico32

<<: !include ../config.yaml

light:
  - id: light0
    name: Garden
    platform: monochromatic
    output: pwm0ch0
    default_transition_length: 500ms

sun:
  latitude: 62.600990°
  longitude: 29.763531°
  on_sunset:
    - then:
        - light.turn_on:
            id: light0
            brightness: 100%

time:
  - platform: sntp
    on_time:
      - cron: 0 0 21 * * *
        then:
          - light.turn_on:
              id: light0
              brightness: 100%
      - cron: 0 0 3 * * *
        then:
          - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO4
    frequency: 19531
