esphome:
  name: light-kitchen-work
  platform: ESP32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-kitchen-work
    password: salaisuus

captive_portal:

light:
  - id: light0
    name: Kitchen, work
    platform: monochromatic
    output: pwm0ch0
    default_transition_length: 500ms

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531
