
substitutions:
  name: light-kitchen-work
  platform: esp32
  board: pico32

<<: !include ../config.yaml

light:
  - id: light0
    name: Kitchen, work
    platform: monochromatic
    output: pwm0ch0
    default_transition_length: 500ms

binary_sensor:
  - id: motion_sensor
    name: Bathroom
    platform: gpio
    device_class: motion
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    filters:
      - delayed_off: 60s
    on_press:
      then:
        - if:
            condition:
              - light.is_off: light0
            then:
              - light.control:
                  id: light0
                  brightness: 10%
              - light.turn_on: light0
    on_release:
        - if:
            condition:
              - light.is_on: light0
              - lambda: 'return id(light0).remote_values.get_brightness() < 0.5;'
            then:
              - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531

sensor:
  - id: temperature0
    name: Kitchen, worklight
    platform: adc
    state_class: measurement
    device_class: temperature
    unit_of_measurement: °C
    accuracy_decimals: 0
    update_interval: 10s
    pin: GPIO33
    attenuation: 6db
    filters:
      - offset: -0.4
      - multiply: 51.2821
