esphome:
  name: light-living-room
  platform: ESP32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-living-room
    password: salaisuus

captive_portal:

light:
  - id: light0
    name: Living room, left
    platform: monochromatic
    output: pwm0ch0
    default_transition_length: 500ms
  - id: light1
    name: Living room, back
    platform: monochromatic
    output: pwm0ch1
    default_transition_length: 500ms

time:
  - platform: sntp
    on_time:
      # morning
      - cron: 0 0 6 * * *
        then:
          - light.turn_on:
              id: light0
              brightness: 30%
      - cron: 0 0 8 * * *
        then:
          - light.control:
              id: light0
              brightness: 50%
      - cron: 0 0 10 * * *
        then:
          - light.turn_off: light0
      # evening
      - cron: 0 0 16 * * *
        then:
          - light.turn_on:
              id: light0
              brightness: 50%
      - cron: 0 0 20 * * *
        then:
          - light.control:
              id: light0
              brightness: 40%
      - cron: 0 0 21 * * *
        then:
          - light.control:
              id: light0
              brightness: 30%
      - cron: 0 0 22 * * *
        then:
          - light.control:
              id: light0
              brightness: 20%
      - cron: 0 0 23 * * *
        then:
          - light.control:
              id: light0
              brightness: 15%
      - cron: 0 0 0 * * *
        then:
          - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531
