
substitutions:
  name: light-living-room
  platform: esp32
  board: pico32

<<: !include ../config.yaml

light:
  - id: light0
    name: Living room
    platform: monochromatic
    output: pwm0
    default_transition_length: 100ms

output:
  - id: pwm0
    type: float
    platform: template
    write_action:
      - output.set_level:
          id: pwm0ch0
          level: !lambda return state;
      - output.set_level:
          id: pwm0ch1
          level: !lambda return state;
      - output.set_level:
          id: pwm0ch2
          level: !lambda return state;
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531
