esphome:
  name: light-patio
  platform: ESP32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-patio
    password: salaisuus

captive_portal:

light:
  - id: light0
    name: Patio
    platform: monochromatic
    output: pwm0ch0
    default_transition_length: 500ms

sun:
  latitude: 62.600990°
  longitude: 29.763531°
  on_sunset:
    - then:
        - light.turn_on:
            id: light0
            brightness: 100%

time:
  - platform: sntp
    on_time:
      - cron: 0 0 4 * * *
        then:
          - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO19
    frequency: 19531
