esphome:
  name: light-pond
  platform: ESP32
  board: pico32

logger:

mqtt:
  broker: iot.lan
  topic_prefix: esphome

ota:
  password: salaisuus

wifi:
  ssid: elukka
  password: salaisuus
  domain: .lan
  ap:
    ssid: esphome-pond
    password: salaisuus

captive_portal:

light:
  - id: light0
    name: Pond
    platform: rgb
    red: pwm0ch0
    green: pwm0ch1
    blue: pwm0ch2
    default_transition_length: 1000ms

time:
  - platform: sntp
    on_time:
      - cron: 0 0 21 * * *
        then:
          - light.turn_on:
              id: light0
              brightness: 100%
              red: 100%
              green: 0%
              blue: 100%
      - cron: 0 0 3 * * *
        then:
          - light.turn_off: light0

output:
  - id: pwm0ch0
    platform: ledc
    pin: GPIO2
    frequency: 19531
  - id: pwm0ch1
    platform: ledc
    pin: GPIO4
    frequency: 19531
  - id: pwm0ch2
    platform: ledc
    pin: GPIO18
    frequency: 19531
